# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Matt code generate

on:
  push:
    branches: [ source ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: install dependence
      run: npm i
      
    - name: build hexo
      run: | 
        npm run clean
        npm run build
        
    - name: generate git info
      run: |
        cd ./public
        git config user.name "Matthew Wang"
        git config user.email "wangmaozhu@foxmail.com"
        git init
        git add .
        git commit -m "update: update static files"

    - name: publish build artifact to github
      uses: dfm/force-push-branch-action@v1
      with:
        github-token: ${{ secrets.MATT_CODE }}
        path: .
        target-branch: main
